services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: vehicles_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data 

  app:
    build:
      context: ./restjpa
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vehicles_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - postgres

volumes:
  postgres_data: