# base name
FROM ubuntu

# author name
MAINTAINER santosh


# RUN apt-update 
# this is the wrong command, now we implement the correct command

# update command
RUN apt update 

# start up executable
CMD [ "echo", "this is my first ubuntu image" ]